title: dmitrytsepelev.dev
description: "A home for my blog posts"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dmitrytsepelev.dev"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: UA-221390545-1

minima:
  social_links:
    twitter: dmitrytsepelev
    github:  dmitrytsepelev

remote_theme: "jekyll/minima"

collections:
  talks:
    output: true

header_pages:
  - talks.md
  - about.md
